# Publish this custom node to the Comfy Registry
# Docs: https://docs.comfy.org/registry/publishing
# Before running:
#  1) Create a repo secret named REGISTRY_ACCESS_TOKEN with your Comfy Registry API key
#     Settings -> Secrets and variables -> Actions -> New repository secret
#  2) Ensure pyproject.toml exists at the repo root with proper [tool.comfy] metadata

name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change to your default branch if different (e.g., master)
    paths:
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

